services:
  portfolio:
    image: cavydev/my-portfolio:latest
    container_name: angular-portfolio-system
    restart: unless-stopped
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.cavydev.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy-network"

networks:
  proxy-network:
    external: true
